services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: elder_app
    volumes:
      - .:/app
    env_file:
      - .env
    environment:
      - MIX_ENV=dev
    ports:
      - "${PHX_PORT:-4000}:${PHX_PORT:-4000}"
    depends_on:
      - db
    command: sh -c "mix deps.get && mix phx.server"
    stdin_open: true
    tty: true

  db:
    image: postgres:16-alpine
    container_name: elder_db
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "${DB_PORT:-5432}:5432"
    volumes:
      - elder_db_data:/var/lib/postgresql/data

volumes:
  elder_db_data:
