defmodule Elder.Asana.TaskDraft do
  @moduledoc """
  Struct and JSON schema for a structured Asana task draft generated by the LLM.
  """

  defstruct [:name, :due_on, :assignee_email, :html_notes]

  @type t :: %__MODULE__{
          name: String.t(),
          due_on: String.t() | nil,
          assignee_email: String.t() | nil,
          html_notes: String.t()
        }

  @schema %{
    "type" => "object",
    "properties" => %{
      "name" => %{
        "type" => "string",
        "description" => "Concise task title derived from the brief (max 100 chars)"
      },
      "due_on" => %{
        "type" => ["string", "null"],
        "description" => "Due date in YYYY-MM-DD format; null if no deadline is mentioned"
      },
      "assignee_email" => %{
        "type" => ["string", "null"],
        "description" =>
          "Email of the responsible person only if explicitly stated; null otherwise"
      },
      "html_notes" => %{
        "type" => "string",
        "description" => "Full task description as a <body>...</body> HTML block"
      }
    },
    "required" => ["name", "html_notes"]
  }

  @max_name_length 100

  @doc "Returns the JSON schema used for structured object generation."
  @spec schema() :: map()
  def schema, do: @schema

  @doc "Builds a TaskDraft from a map, enforcing required fields and capping the name length."
  @spec from_map(map()) :: {:ok, t()} | {:error, :invalid_task_draft}
  def from_map(%{"name" => name, "html_notes" => html} = map)
      when is_binary(name) and byte_size(name) > 0 and
             is_binary(html) and byte_size(html) > 0 do
    {:ok,
     %__MODULE__{
       name: String.slice(name, 0, @max_name_length),
       due_on: string_or_nil(map["due_on"]),
       assignee_email: string_or_nil(map["assignee_email"]),
       html_notes: String.trim(html)
     }}
  end

  def from_map(_invalid), do: {:error, :invalid_task_draft}

  defp string_or_nil(s) when is_binary(s) and byte_size(s) > 0, do: s
  defp string_or_nil(_value), do: nil
end
